### ISSUE TITLE
Add dark theme and light theme feature

### ISSUE THREAD

**Issue by silkie261001** [ContriHUB/PlayTopia#2]
There should be one button or slider to turn light theme or dark theme

**Comment by theDevSoham** [comment]
Hey @silkie261001 can I give a go to this issue? If so please assign me

**Comment by silkie261001** [comment]
assigned

**Comment by theDevSoham** [comment]
@silkie261001 I'm getting error on Mongoose connect. Could you please help me out. I checked that the code is using process.env.MONGO_URI at `backend/server.js` on line number `118`. Currently, the repo doesn't have any .env.example which I can convert to .env

![Screenshot from 2023-10-07 13-07-44](https://github.com/ContriHUB/PlayTopia/assets/79685489/a3e29e58-c789-413e-be38-f0e0a3b5bb48)

**Comment by rituraj12797** [comment]
please assign issue to me

**Comment by sharmavasant** [comment]
can u assign me this issue

**Comment by ujjwal13818** [comment]
Hi @silkie261001 sir, a simple if-else statement in javascript with some CSS properties will do the work.  Please assign this to me.

**Comment by shikhartheone** [comment]
Maam/Sir,
I have been tasked with addressing the current issue on ContriHub. However, I kindly request an extension of the deadline, as I am currently halfway through the resolution process. Please consider reassigning this issue to me, allowing for the necessary additional time to ensure its successful completion. The original time allocated for this assignment is expected to expire at approximately 3:40 PM in ContriHub.
I kindly request that this issue be reassigned to me to allow for the necessary time extension to ensure a thorough and successful resolution.

**Comment by silkie261001** [comment]
It is a competition and it is not allowed

**Comment by harshit1142** [comment]
I am facing issue while registration "Error : try again "

{ username: 'user1233', email: 'pandey@gmail.com', password: '123456' }
user register request came
register fail => MongoServerError: E11000 duplicate key error collection: playTopia.users index: email_1 dup key: { email: "pandey@gmail.com" }
    at C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\operations\insert.js:53:33
    at C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\connection_pool.js:333:25
    at C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\sdam\server.js:210:17
    at handleOperationResult (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\sdam\server.js:326:20)
    at Connection.onMessage (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\connection.js:243:9)
    at MessageStream.<anonymous> (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\connection.js:61:60)
    at MessageStream.emit (node:events:514:28)
    at processIncomingData (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\message_stream.js:125:16)
    at MessageStream._write (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12) {
  index: 0,
  code: 11000,
  keyPattern: { email: 1 },
  keyValue: { email: 'pandey@gmail.com' },
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by silkie261001** [comment]
have you connected db

**Comment by harshit1142** [comment]
> have you connected db

Yes Ma'am

**Comment by silkie261001** [comment]
do you have .env file

**Comment by harshit1142** [comment]
> do you have .env file

No , it is hidden by .gitignore file


Error: 
{ username: 'user1233', email: 'pandey@gmail.com', password: '123456' }
user register request came
register fail => MongoServerError: E11000 duplicate key error collection: playTopia.users index: email_1 dup key: { email: "pandey@gmail.com" }
    at C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\operations\insert.js:53:33
    at C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\connection_pool.js:333:25
    at C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\sdam\server.js:210:17
    at handleOperationResult (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\sdam\server.js:326:20)
    at Connection.onMessage (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\connection.js:243:9)
    at MessageStream.<anonymous> (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\connection.js:61:60)
    at MessageStream.emit (node:events:514:28)
    at processIncomingData (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\message_stream.js:125:16)
    at MessageStream._write (C:\Users\91830\Desktop\PlayTopia\backend\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12) {
  index: 0,
  code: 11000,
  keyPattern: { email: 1 },
  keyValue: { email: 'pandey@gmail.com' },
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by silkie261001** [comment]
send your email id i will give .env file then try

**Comment by harshit1142** [comment]
> send your email id i will give .env file then try

harshitinfinix8@gmail.com
